### ISSUE TITLE
Add (Siren)

### ISSUE THREAD

**Issue by mrmajik45** [muukii/Pixel#10]
http://sabintsev.com/Siren/

Notifys people when there is an update.

**Comment by muukii** [comment]
@mrmajik45 
I think that should be used in Application, right?

**Comment by mrmajik45** [comment]
Yes the app.

**Comment by muukii** [comment]
@mrmajik45 
Hmm, You mean Pixel should include Siren?
Pixel is a library, not application.

**Comment by mrmajik45** [comment]
Oh. I mean it notifys when there is an update... crap. (Everything feels
bad)
