### ISSUE TITLE
How to customize the UI with XIB or storyboard ?

### ISSUE THREAD

**Issue by iBearKh** [muukii/Pixel#17]

**Comment by muukii** [comment]
@khoozhiyan1997 
Thank you for your issue.
I think this issue relates to https://github.com/muukii/Pixel/issues/18.

You can use UI anything you want with setting class you created to Option struct.
But, Pixel cannot initialize UIView created by IB.
As a workaround, you avoid this problem with creating container UIView.
just like this.

firstly, chose a base class you want to customize.
You can find this from Option struct.

<img width="906" alt="screen shot 2018-12-26 at 5 04 23" src="https://user-images.githubusercontent.com/1888355/50426231-c8b1f580-08cb-11e9-90ce-7196a1ac3a6a.png">

If you want to customize EditMenuControl from scratch with IB.

```swift
class ContainerView : EditMenuControlBase {

  public required override init(context: PixelEditContext) {
    super.init(context: context)
    let bodyView = // initialize from IB
    addSubview(bodyView)
  }
}
```

Let me know if you have any questions.
