### ISSUE TITLE
'ColorCubeStorage' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by adxworld** [muukii/Pixel#20]
Add ColorCube filter is throwing me this error. Is there a work around?

Also what is the `identifier` and `lutimage` property in the :
`let filter = FilterColorCube(
            name: "Filter Name",
            identifier: "Filter Identifier",
            lutImage: lutImage,
            dimension: 64
        )`

**Comment by muukii** [comment]
@adxworld 
Sorry, that's for sure.
I've released [0.0.6](https://github.com/muukii/Pixel/releases/tag/0.0.6) with fixing this.

**Comment by muukii** [comment]
about identifier, you should set any value as uniquely.
about lutImage, word of ColorCube means using LUT Image (Look Up Table),
 you can find information about this here. 
https://en.wikipedia.org/wiki/Lookup_table
https://medium.com/the-bergen-company/recreating-vsco-filters-in-darkroom-291114051a0e

**Comment by adxworld** [comment]
Thanks for being prompt. 
And got it. Will read them. 

BTW, great library !

**Comment by adxworld** [comment]
Also, Is there a way to just have the editor and have the filter option removed?

**Comment by muukii** [comment]
@adxworld 

Currently, the answer is No. (for easily)
But, You can customize UI and you may find the information below.
https://github.com/muukii/Pixel/issues/18
https://github.com/muukii/Pixel/issues/17
