### ISSUE TITLE
Preview of image with filter not showed

### ISSUE THREAD

**Issue by arturmichna** [muukii/Pixel#33]
Version of Pixel: 0.0.9
Xcode: 11.0 beta 6
iOS: 13 beta

As in attached screenshoot there is an issue with previewing images with filters on newest iOS 13 beta.

![IMG_0001 2](https://user-images.githubusercontent.com/8112955/64328196-51417380-cfcd-11e9-9e67-63c92d8bcc50.PNG)

**Comment by muukii** [comment]
Thank you.
I’ve also found that issue. And then that has been fixed as temporally.
https://github.com/muukii/Pixel/pull/32
Could you check that behavior on this branch?

**Comment by gofundmedevs** [comment]
Hi Muukii, I am facing the same issue on iOS 13, I just wanted to check when will these changes be merged to master?

**Comment by muukii** [comment]
I'm sorry.
Actually, we can merge this.
I'll do this.

**Comment by arturmichna** [comment]
Issue has been fixed in latest version
