### ISSUE TITLE
Code indentation is two spaces

### ISSUE THREAD

**Issue by weifans** [muukii/Pixel#35]
**Why is the code indentation two spaces?**
**This is not a standard code format. I tried to format the code, but it didn't work. What changed in the project?**

**Comment by cyanzhong** [comment]
Why do you think two-spaces is not a **standard** style?

Here are some facts:
- Google's guideline uses 2-spaces: https://google.github.io/swift/ 
- Raywenderlich uses 2-spaces: https://github.com/raywenderlich/swift-style-guide
- Swift source code uses 2-spaces as well: https://github.com/apple/swift/blob/master/stdlib/public/core/Codable.swift
- LinkedIn uses 4-spaces: https://github.com/linkedin/swift-style-guide

See? It's all about **preferences**, not **standards**. I personally prefer 2-spaces, too.

I don't see any trouble for using 2-spaces, as long as you set your Xcode indentation properly.
